version: '3.5'
services:
  simplifier-d2wrnew:
    container_name: ${SIMPLIFIER_HOST}
    image: simplifierag/runtime-prerelease:7.8
    restart: always
    volumes:
      - /var/lib/simplifier/data/d2wrnew:/opt/simplifier/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - DB=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DB=d2wrnew
      - PLUGINLIST=keyValueStorePlugin,pdfPlugin,captcha,contentRepoPlugin,jsonStore
      - SECOND_SEED=launchpad-d2wrnew
      - MODULE_HOST=simplifier-d2wrnew
      - SIMPLIFIER_HOST=${SIMPLIFIER_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${ROUTER_NAME}.middlewares=${ROUTER_NAME}_cors_header"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accesscontrolallowheaders=DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,SimplifierToken,SimplifierApp,SimplifierModule,SimplifierModuleInterface,sap-cancel-on-close,sap-contextid-accept,MaxDataServiceVersion,DataServiceVersion,Content-Length,SimplifierApiKey"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accesscontrolalloworiginList=https://${SIMPLIFIER_HOSTNAME},ionic://localhost"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accesscontrolmaxage=1728000"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.addvaryheader=true"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.${ROUTER_NAME}_cors_header.headers.accessControlExposeHeaders=remainingTokenLifetime"
    networks:
      - simplifier-app-network

  launchpad-d2wrnew:
    container_name: launchpad-d2wrnew
    image: simplifierag/launchpad-prerelease:snapshot
    restart: always
    environment:
      - SIMPLIFIER_HOST=${SIMPLIFIER_HOST}
      - SECOND_SEED=launchpad-d2wrnew
      - THIRD_SEED=workflow-designtime-d2wrnew
      - MODULE_HOST=launchpad-d2wrnew
    networks:
      - simplifier-app-network

  workflow-designtime-d2wrnew:
    container_name: workflow-designtime-d2wrnew
    image: simplifierag/workflow-designtime
    init: true
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=d2wrnew_wdt
      - DB_HOST=mysql
      - DB_PORT=3306
      - SIMPLIFIER_HOST=${SIMPLIFIER_HOST}
      - SECOND_SEED=launchpad-d2wrnew
      - THIRD_SEED=workflow-designtime-d2wrnew
      - MODULE_HOST=workflow-designtime-d2wrnew
    volumes:
      - "/var/lib/simplifier/data/d2wrnew/workflowDesigntime:/opt/workflowDesigntime"
    networks:
      - simplifier-app-network

  workflow-runtime-d2wrnew:
    container_name: workflow-runtime-d2wrnew
    image: simplifierag/workflow-runtime-prerelease:snapshot
    init: true
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=d2wrnew_wrt
      - DB_HOST=mysql
      - DB_PORT=3306
      - SIMPLIFIER_HOST=${SIMPLIFIER_HOST}
      - SECOND_SEED=launchpad-d2wrnew
      - THIRD_SEED=workflow-designtime-d2wrnew
      - MODULE_HOST=workflow-runtime-d2wrnew
    #    volumes:
    #      - "/var/lib/simplifier/data/d2wrnew/workflowRuntime:/home/workflow-runtime/logback-local.include.xml:ro"
    networks:
      - simplifier-app-network

networks:
  simplifier-app-network:
    external: true